name: EntitledSample
options:
  bundleIdPrefix: dev.entitled.sample
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
packages:
  Entitled:
    path: ../..
targets:
  EntitledSample:
    type: application
    platform: iOS
    sources:
      - EntitledSample
    dependencies:
      - package: Entitled
        product: EntitledKit
    info:
      path: EntitledSample/Info.plist
      properties:
        UILaunchScreen: {}
  EntitledSampleTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
    sources:
      - EntitledSampleTests
      - path: Entitled.storekit
        buildPhase: resources
    dependencies:
      - target: EntitledSample
      - package: Entitled
        product: EntitledKit
  EntitledSampleUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
    sources:
      - EntitledSampleUITests
      - path: Entitled.storekit
        buildPhase: resources
    dependencies:
      - target: EntitledSample
schemes:
  EntitledSample:
    build:
      targets:
        EntitledSample: all
        EntitledSampleTests: [test]
        EntitledSampleUITests: [test]
    run:
      storeKitConfiguration: Entitled.storekit
    test:
      targets:
        - EntitledSampleTests
        - EntitledSampleUITests
